### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by loganpowell** [dabit3/create-rn-web-app#1]
Thank you for creating this starter tool! I'm having problems getting up and running. Upon global installation of the CLI and then trying to use it, I get:

```
create-rn-web-app rn-web-app-test
----------------------------------------------------------
child_process.js:383
    throw new TypeError('"file" argument must be a non-empty string');
    ^

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:383:11)
    at exports.spawn (child_process.js:496:38)
    at Object.<anonymous> (C:\Users\surface\AppData\Roaming\npm\node_modules\create-rn-web-app\bin\cli.js:16:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)

```

Any pointers?

**Comment by vladp** [comment]
receiving the same error as reporter of the issue above.
seems like the module does not work.

> 
> ----------------------------------------------------------
> child_process.js:381
>     throw new TypeError('"file" argument must be a non-empty string');
>     ^
> 
> TypeError: "file" argument must be a non-empty string
>     at normalizeSpawnArguments (child_process.js:381:11)
>     at exports.spawn (child_process.js:494:38)
>     at Object.<anonymous> (C:\Users\v\AppData\Roaming\npm\node_modules\create-rn-web-app\bin\cli.js:16:3)
>     at Module._compile (module.js:649:30)
>     at Object.Module._extensions..js (module.js:660:10)
>     at Module.load (module.js:561:32)
>     at tryModuleLoad (module.js:501:12)
>     at Function.Module._load (module.js:493:3)
>     at Function.Module.runMain (module.js:690:10)
>     at startup (bootstrap_node.js:194:16)

**Comment by Alfran007** [comment]
Any update? I am receiving the same error as above!
